#!/bin/bash

# splitting
bcftools norm \
    -m - input.vcf.gz \
    --threads 10 \
    -Oz \
    –o temp1.vcf.gz

# unifying variant IDs
bcftools annotate \
    -x ID \
    -I +'%CHROM:%POS:%REF:%ALT' temp1.vcf.gz \
    --threads 10 \
    -Oz \
    –o temp2.vcf.gz

# getting PASS variants for vcf
bcftools view \
    -f PASS temp2.vcf.gz \
    -Oz \
    –o temp3.vcf.gz

# mergin wes/wgs vcf
# repeat earlier steps for all vcf files changing temp3.vcf.gz to a unique ID accordingly
# create a merged list
ls *.vcf.gz > merge.list

# merging all niddk vcfs
bcftools merge \
    -l merge. \
    --Oz \
    -o all-NIDDK-Sequencing.vcf.gz

# converting to plink format
plink \
    --vcf all-NIDDK-Sequencing.vcf.gz \
    --const-fid \
    --make-bed \
    --out all-NIDDK-WES-WGS

# converting GSA files to plink binary format
find ./Plink_Files/ -name "*.ped" |
    while read line
    do
        file=${line%.ped}
        outname=`echo $line|cut -d '/' -f 3`
        echo $outname
        plink \
            --file $file \
            --make-bed \
            --out ./merge-plinks-GSA/$outname
    done

# unifying variant IDs
ls *.bim |
    while read line
    do
        awk '{print $2"\t"$1":"$4":"$6":"$5}' $line> update.ids
        name=${line%.bim}
        plink \
            --bfile $name \
            --update-map update.ids \
            --update-name \
            --make-bed \
            --out $name-newID
    done

# merging gsa
ls *.bim |
    while read line
    do
        name=${line%.bim}
        echo "$name.bed $name.bim $name.fam" >> merge.list
    done

plink \
    --merge-list merge.list \
    --make-bed \
    --out merged-GSA

plink \
    --bfile merged-GSA \
    --fill-missing-a2 \
    --make-bed \
    --out merged-GSA-A2fill

# liftover to hg38 and preparing plink format
grep -E "I|D" merged-GSA-A2fill.bim | cut -f 2 > to-be-excluded.list           # removing variants in malformed format.

plink \
    --bfile merged-GSA-A2fill \
    --exclude to-be-excluded.list \
    --make-bed \
    --out merged-GSA-A2fill-clean

plink \
    --bfile merged-GSA-A2fill-clean \
    --recode vcf bgz \
    --output-chr chr26 \
    --out all-GSA-clean

bcftools view \
    -r chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chr23 all-GSA-clean.vcf.gz \
    -Oz \
    -o allGSA-chr1-23.vcf.gz

picard \
    -LiftoverVcf \
    I=allGSA-chr1-23.vcf.gz \
    O=all-GSA-hg38.vcf.gz \
    CHAIN=../../../reference/hg19ToHg38.over.chain \
    REJECT=rejec.vcf.gz \
    R=../../../reference/hg38.fa                                              # first round liftover to get rejected site due to strands flipped

zcat rejec.vcf.gz| grep -v "#"| cut -f 3 > to-be-flipped.list

plink  \
    --bfile merged-GSA-A2fill-clean \
    --flip to-be-flipped.list \
    --make-bed \
    --out merged-GSA-A2fill-clean-flipped

plink \
    --bfile merged-GSA-A2fill-clean-flipped \
    --recode vcf bgz \
    --output-chr chr26 \
    --out all-GSA-clean-flipped

bcftools view \
    -r chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chr23 all-GSA-clean-flipped.vcf.gz \
    -Oz \
    -o allGSA-chr1-23-flipped.vcf.gz

picard LiftoverVcf \
    I=allGSA-chr1-23-flipped.vcf.gz \
    O=all-GSA-hg38-flipped.vcf.gz \
    CHAIN=../../../reference/hg19ToHg38.over.chain \
    REJECT=rejec.vcf.gz \
    R=../../../reference/hg38.fa

plink \
    --vcf ./gsa/merge-plinks-GSA/newIDs/all-GSA-hg38-flipped-newID.vcf.gz \
    --const-fid \
    --allow-extra-chr \
    --make-bed \
    --out ./duplicates-gsa-sequencing gsa-hg38-lifted

# merging gsa and sequencing to perform king analysis
plink \
    --bfile gsa-hg38-lifted \
    --extract all-NIDDK-WES-WGS.bim  \
    --allow-extra-chr \
    --make-bed –out temp1

plink \
    --bfile all-NIDDK-WES-WGS \
    --extract gsa-hg38-lifted.bim  \
    --allow-extra-chr \
    --make-bed –out temp2

plink \
    --bfile temp1 \
    --bmerge temp2.bed temp2.bim temp2.fam \
    --make-bed \
    --out merged-gsa-sequencing

king \
    -b merged-gsa-sequencing.bed \
    --related \
    --degree 2 \
    --prefix related-grade2
