#!/bin/bash

# This script requires conda as dependency
# maintainer: christopher.tastad@mssm.edu

# Exit immediately if a command exits with a non-zero status
set -euo pipefail

# Function that will be called if any command in the script fails
function on_failure {
    echo "The script" "${0##*/}" "has failed"
}

# Trap ERR signal and call on_failure function
trap on_failure ERR

. ./setup/preamble
INPUTS=$1 

# Activate king-dedup environment
conda activate king-dedup

# Run main program and pipe output to log.txt file in output directory.
./main $OUT_DIR $INPUTS 2>&1 | tee -a $OUT_DIR/log.txt

# Remove temporary directory.
rm -rf $OUT_DIR/tmp

# Deactivate king-dedup environment.
conda deactivate

