#!/bin/bash

eval "$(conda shell.bash hook)"

# Install packages if they aren't already installed
declare -a TOOLS=(
"king"
"bcftools"
"picard"
"plink"
)

# Check if conda is installed
if ! command -v conda &> /dev/null
then
    echo "conda could not be found"
    exit
fi

# Create environment if it doesn't exist
if ! conda env list | grep -q "king-dedup"
then
    conda create --name king-dedup -y
    conda activate king-dedup
    for i in "${TOOLS[@]}"
    do
        conda install -y "$i"
    done
fi

# Deactivate environment
conda deactivate
