#!/bin/bash

# Get current timestamp
TIMESTAMP=$(date +"%Y-%m-%d_%H.%M.%S")

# Create output directory with timestamp
OUT_DIR="output/output_$TIMESTAMP"
mkdir -p $OUT_DIR $OUT_DIR/tmp
export OUT_DIR

# Activate conda environment
eval "$(conda shell.bash hook)"

# Declare an array of tools to install
declare -a TOOLS=(
"king"
"bcftools"
"picard"
"plink"
"plink2"
)

# Check if conda is installed
if ! command -v conda &> /dev/null
then
    echo "conda could not be found"
    exit
fi

# Check if king-dedup environment exists. If not, create it and install tools.
if ! conda env list | grep -q "king-dedup"
then
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda config --set channel_priority strict
    conda create --name king-dedup python==2.7.18 -y
    conda activate king-dedup
    for i in "${TOOLS[@]}"
    do
        conda install -y "$i"
    done
    pip install snpflip
    conda deactivate
fi

# Pull down liftover files
wget \
    https://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz \
    -O $OUT_DIR/tmp/hg19ToHg38.over.chain.gz

wget \
    https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz \
    -O $OUT_DIR/tmp/hg38.fa.gz 

gzip -d $OUT_DIR/tmp/*.gz

